version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Environment ready.
  build:
    commands:
      - echo Building Vue project...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - ls ./dist/
      - ls ./dist/shop/

artifacts:
  files:
    - dist/**/*
    #- appspec.yaml
